# Generated by Django 4.2 on 2024-04-10 08:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0002_category_image_places"),
    ]

    operations = [
        migrations.RenameField(
            model_name="places",
            old_name="Longitude",
            new_name="Lon",
        ),
    ]
