# Generated by Django 4.2 on 2024-04-11 06:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0003_rename_longitude_places_lon"),
    ]

    operations = [
        migrations.AddField(
            model_name="places",
            name="my_id",
            field=models.IntegerField(default=0),
        ),
    ]
